Repository ROCm/MITuna, pull requests merged in 2022-09, with the labels that each got.

#761 Import script update: create session for perf_db import
  tests/test_analyze_parse_db.py
  tests/test_find.py
  tuna/analyze_parse_db.py
  tuna/find_db.py
  tuna/import_db.py
  tuna/miopen_tables.py
  tuna/session.py
  vars/utils.groovy
Labels: enhancement

#769 coverage_fixes
  .coverage
  README.md
  requirements.txt
  tests/covscripts/coverage_parse_attributes.py
  utils/coverage_files/coverage.json
  utils/coverage_files/coverage_percentage.txt
Labels: bug

#773 SQLAlchemy indices
  tuna/db_tables.py
  tuna/find_db.py
  tuna/miopen_db_helpers.py
  tuna/miopen_tables.py
Labels: enhancement

#767 Populate + Export Golden Table
  Jenkinsfile
  doc/GoldDB.md
  tests/dummy_machine.py
  tests/test_abort_file.py
  tests/test_add_session.py
  tests/test_fin_builder.py
  tests/test_mmi.py
  tests/test_update_golden.py
  tests/test_worker.py
  tests/utils.py
  tuna/db_tables.py
  tuna/export_db.py
  tuna/fin_eval.py
  tuna/fin_utils.py
  tuna/find_db.py
  tuna/go_fish.py
  tuna/miopen_db_helpers.py
  tuna/miopen_tables.py
  tuna/populate_golden.py
  tuna/session.py
  tuna/update_golden.py
  tuna/worker_interface.py
  vars/utils.groovy
Labels: bug, enhancement

#768 Merge staging branch into master
  CONTRIBUITING.md
  Dockerfile
  README.md
  doc/TuningCycle.md
  dockerfiles/rocm_base/Dockerfile
  requirements.txt
  setup.py
  tests/test_fin_class.py
  tests/test_fin_utils.py
  tuna/builder.py
  tuna/dbBase/base_class.py
  tuna/evaluator.py
  tuna/export_db.py
  tuna/fin_builder.py
  tuna/fin_class.py
  tuna/fin_eval.py
  tuna/fin_utils.py
  tuna/find_db.py
  tuna/go_fish.py
  tuna/helper.py
  tuna/import_db.py
  tuna/metadata.py
  tuna/metrics.py
  tuna/miopen_db_helpers.py
  tuna/miopen_tables.py
  tuna/session.py
  tuna/tables.py
  tuna/utils/db_utility.py
  tuna/worker_interface.py
  utils/recurrent_cfgs/resnet50_4jobs.txt
  vars/utils.groovy
Labels: enhancement
